package lk.ijse.riceMil.util;

public enum Routes {
    ADMIN_VIEW,CUSTOMER_FORM,ITEM_FORM,MAIN_FORM,ORDER_FORM,PLACE_ORDER,SUPPLIER_FORM,EMPLOYEE_FORM,ATTENDANCE_FORM,
    SALARY_FORM,PURCHASE_ORDER_FORM,DELIVER_ORDER_FORM,PAYMENT_FORM,REPORT_FORM,DETAIL_FORM,CASHIER_VIEW

}
